"""integrations (ADR 0016, expand only)

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-09 14:26:13.408544
"""
from alembic import op
import sqlalchemy as sa
import app.db.types


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('home_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('last_sync_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('yandex')", name=op.f('ck_integrations_kind_valid')),
    sa.CheckConstraint("status IN ('pending','ok','error')", name=op.f('ck_integrations_status_valid')),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], name=op.f('fk_integrations_home_id_homes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('home_id', 'kind', name='uq_integrations_home_kind')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_home_id'), ['home_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_home_id'))

    op.drop_table('integrations')
    # ### end Alembic commands ###
